using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.OpenApi.Models;
using Microsoft.OpenApi.Models.Interfaces;

namespace Conduit.WebApi.Configuration;

static class OpenApiExtension
{
    internal static IServiceCollection AddConduitOpenApiSetup(this IServiceCollection services)
    {
        return services.AddOpenApi(options =>
        {
            options.AddDocumentTransformer<DocumentInfoTransformer>();
            options.AddDocumentTransformer<BearerSecuritySchemeTransformer>();
        });
    }

    internal static IEndpointConventionBuilder MapConduitOpenApi(this IEndpointRouteBuilder app)
    {
        return app.MapOpenApi();
    }

    sealed class DocumentInfoTransformer() : IOpenApiDocumentTransformer
    {
        public Task TransformAsync(OpenApiDocument document, OpenApiDocumentTransformerContext context, CancellationToken cancellationToken)
        {
            document.Info = new()
            {
                Title = "RealWorld Conduit API",
                Version = "1.0.0",
                Description = "Conduit API documentation",
                Contact = new()
                {
                    Name = "RealWorld",
                    Url = new Uri("https://realworld-docs.netlify.app/")
                },
                License = new()
                {
                    Name = "MIT",
                    Url = new Uri("https://opensource.org/licenses/MIT")
                }
            };
            return Task.CompletedTask;
        }
    }

    sealed class BearerSecuritySchemeTransformer(IAuthenticationSchemeProvider authenticationSchemeProvider) : IOpenApiDocumentTransformer
    {
        public async Task TransformAsync(OpenApiDocument document, OpenApiDocumentTransformerContext context, CancellationToken cancellationToken)
        {
            var authenticationSchemes = await authenticationSchemeProvider.GetAllSchemesAsync();
            if (authenticationSchemes.Any(authScheme => authScheme.Name == "Bearer"))
            {
                var requirements = new Dictionary<string, IOpenApiSecurityScheme>
                {
                    ["Bearer"] = new OpenApiSecurityScheme
                    {
                        Name = "Authorization",
                        Description = @"For accessing the protected API resources, you must have received a a valid JWT token after registering or logging in. This JWT token must then be used for all protected resources by passing it in via the 'Authorization' header.
 
A JWT token is generated by the API by either registering via /users or logging in via /users/login.
 
The following format must be in the 'Authorization' header :
 
     Token xxxxxx.yyyyyyy.zzzzzz",
                        Type = SecuritySchemeType.ApiKey,
                        //Scheme = "bearer",
                        In = ParameterLocation.Header,
                        BearerFormat = "JWT",
                    }
                };
                document.Components ??= new OpenApiComponents();
                document.Components.SecuritySchemes = requirements;
            }
        }
    }
}

/* 
static class OpenApiExtension
{
    public static IServiceCollection AddConduitOpenApiSetup(this IServiceCollection services)
    {
        services.AddSwaggerGen(x =>
        {
            x.IncludeXmlComments(XmlCommentsFilePath);
            x.SupportNonNullableReferenceTypes();
            x.SchemaFilter<OpenApiNonNullableFalseFilter>();
            x.SchemaFilter<OpenApiRequiredMemberFilter>();
            x.EnableAnnotations();

            x.AddSecurityDefinition(
                "Bearer",
                new OpenApiSecurityScheme
                {
                    In = ParameterLocation.Header,
                    Description = "Please insert JWT with Bearer into field",
                    Name = "Authorization",
                    Type = SecuritySchemeType.ApiKey,
                    BearerFormat = "JWT"
                }
            );

            x.AddSecurityRequirement(
                new OpenApiSecurityRequirement()
                {
                    {
                        new OpenApiSecurityScheme
                        {
                            Reference = new OpenApiReference
                            {
                                Type = ReferenceType.SecurityScheme,
                                Id = "Bearer"
                            }
                        },
                        Array.Empty<string>()
                    }
                }
            );
            x.SwaggerDoc("v1", new OpenApiInfo
            {
                Title = "RealWorld Conduit API",
                Version = "1.0.0",
                Description = "Conduit API documentation",
                Contact = new OpenApiContact
                {
                    Name = "RealWorld",
                    Url = new Uri("https://www.realworld.how")
                },
                License = new OpenApiLicense
                {
                    Name = "MIT License",
                    Url = new Uri("https://opensource.org/licenses/MIT")
                }
            });
            //x.CustomSchemaIds(y => y.FullName);
        });

        return services;
    }

    public static WebApplication UseConduitOpenApi(this WebApplication app)
    {
        app.UseSwagger(c =>
        {
            c.RouteTemplate = "api-docs/{documentName}/openapi.json";
            c.PreSerializeFilters.Add((swagger, httpReq) =>
            {
                swagger.Servers = new List<OpenApiServer> { new OpenApiServer { Url = $"{httpReq.Scheme}://{httpReq.Host.Value}/api" } };
            });
        });

        if (app.Environment.IsDevelopment())
        {
            app.UseSwaggerUI(c =>
            {
                c.RoutePrefix = "api-docs";
                c.SwaggerEndpoint("v1/openapi.json", "RealWorld API V1");
            });
        }

        return app;
    }

    private static string XmlCommentsFilePath
    {
        get
        {
            string basePath = AppContext.BaseDirectory;
            string fileName = typeof(Program).Assembly.GetName().Name + ".xml";
            return Path.Combine(basePath, fileName);
        }
    }
}
 */
