using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.OpenApi;


namespace Conduit.WebApi.Configuration;

static class OpenApiExtension
{
    internal static IServiceCollection AddConduitOpenApi(this IServiceCollection services)
    {
        return services.AddOpenApi(options =>
        {
            options.UseDocumentInfo();
            options.UseJwtBearerAuthentication();
        });
    }

    internal static WebApplication MapConduitOpenApi(this WebApplication app)
    {
        app.MapOpenApi("openapi/v1.json");
        app.UseSwaggerUI(options =>
        {
            options.SwaggerEndpoint("openapi/v1.json", "v1");
        });

        return app;
    }

    static OpenApiOptions UseDocumentInfo(this OpenApiOptions options)
    {
        options.AddDocumentTransformer((document, context, CancellationToken) =>
        {
            document.Info = new()
            {
                Title = "RealWorld Conduit API",
                Version = "1.0.0",
                Description = "Conduit API documentation",
                Contact = new()
                {
                    Name = "RealWorld",
                    Url = new Uri("https://realworld-docs.netlify.app/")
                },
                License = new()
                {
                    Name = "MIT",
                    Url = new Uri("https://opensource.org/licenses/MIT")
                }
            };

            return Task.CompletedTask;
        });

        return options;
    }

    static OpenApiOptions UseJwtBearerAuthentication(this OpenApiOptions options)
    {
        var securityScheme = new OpenApiSecurityScheme()
        {
            Name = "Authorization",
            Description = @"For accessing the protected API resources, you must have received a a valid JWT token after registering or logging in. This JWT token must then be used for all protected resources by passing it in via the 'Authorization' header.
 
A JWT token is generated by the API by either registering via /users or logging in via /users/login.
 
The following format must be in the 'Authorization' header :
 
     Token xxxxxx.yyyyyyy.zzzzzz",
            Type = SecuritySchemeType.ApiKey,
            In = ParameterLocation.Header,
            Scheme = JwtBearerDefaults.AuthenticationScheme,
            BearerFormat = "JWT"
        };

        options.AddDocumentTransformer((document, context, CancellationToken) =>
        {
            document.Components ??= new();
            document.Components.SecuritySchemes = new Dictionary<string, IOpenApiSecurityScheme>
            {
                ["Token"] = securityScheme
            };

            return Task.CompletedTask;
        });

        options.AddOperationTransformer((operation, context, CancellationToken) =>
        {
            var hasAuthorize = context.Description.ActionDescriptor.EndpointMetadata
                            .OfType<AuthorizeAttribute>().Any();

            if (hasAuthorize)
            {
                operation.Security ??= new List<OpenApiSecurityRequirement>();
                operation.Security.Add(new OpenApiSecurityRequirement
                {
                    [new OpenApiSecuritySchemeReference("Token", context.Document)] = []
                });
            }

            return Task.CompletedTask;
        });

        return options;
    }
}
