# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  restapi:
    image: conduit/rest-api:dev
    build:
      context: ../
      dockerfile: docker/conduit-rest-api/Dockerfile
      args:
      - configuration=Debug
    ports:
    - 8080:8080
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    volumes:
    #- ~/.vsdbg:/remote_debugger:rw
    - db-data:/app/db
volumes:
  db-data: