# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  restapi:
    image: conduit/rest-api
    build:
      context: ../
      dockerfile: docker/conduit-rest-api/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - db-data:/app/db
volumes:
  db-data: