<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../ServiceDefaults/Conduit.Host.ServiceDefaults.csproj" />
    <ProjectReference Include="../../Modules/Articles/Api/Conduit.Articles.Api.csproj" />
    <ProjectReference Include="../../Modules/Articles/Infrastructure/Conduit.Articles.Infrastructure.csproj" />
    <ProjectReference Include="../../Modules/Identity/Api/Conduit.Identity.Api.csproj" />
    <ProjectReference Include="../../Modules/Identity/Application/Conduit.Identity.Application.csproj" />
    <ProjectReference Include="../../Modules/Identity/Contracts/Conduit.Identity.Contracts.csproj" />
    <ProjectReference Include="../../Modules/Identity/Infrastructure/Conduit.Identity.Infrastructure.csproj" />
    <ProjectReference Include="../../Modules/Tags/Contracts/Conduit.Tags.Contracts.csproj" />
    <ProjectReference Include="../../Modules/Tags/Core/Conduit.Tags.Core.csproj" />
    <ProjectReference Include="../../Shared/Application/Conduit.Shared.Application.csproj" />
    <ProjectReference Include="../../Shared/Infrastructure/Conduit.Shared.Infrastructure.csproj" />
  </ItemGroup>
</Project>
